services:
  pgdb:
    image: postgres:latest
    restart: on-failure
    ports:
      - ${PORT_POSTGRES}:${PORT_POSTGRES}
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    container_name: mee-postgres
  
  proxy:
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - ./.env
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.template.conf:/etc/nginx/nginx.template.conf
      - /etc/ssl/mee.social:/etc/ssl/mee.social
    depends_on:
      - backend
      - client
    container_name: mee-proxy
    command: /bin/bash -c "envsubst < etc/nginx/nginx.template.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
  
  backend:
    build:
      context: .
    restart: always
    ports:
      - ${PORT_BACKEND}
    env_file:
      - path: ./.env
    depends_on:
      - pgdb
    container_name: mee-backend
  
  client:
    build:
      context: ../mee
      args:
        CLIENT_WEB_BASE_PATH: ${CLIENT_WEB_BASE_PATH}
        PORT_FRONTEND: ${PORT_FRONTEND}
    restart: always
    ports:
      - ${PORT_FRONTEND}
    env_file:
      - path: ./.env
    container_name: mee-client

  landing:
    build:
      context: ../mee-landing
      args:
        PORT: ${PORT_LANDING}
    restart: always
    ports:
      - ${PORT_LANDING}
    env_file:
      - path: ./.env
    container_name: mee-landing


volumes:
  pgdata: