services:
  pgdb:
    image: postgres:latest
    restart: on-failure
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    container_name: mee-postgres
  
  proxy:
    image: nginx:latest
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - ./.env
    volumes:
      # - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx.template.conf:/etc/nginx/nginx.template.conf
      - /etc/ssl/mee.social:/etc/ssl/mee.social
    depends_on:
      - backend
      - client
    container_name: mee-proxy
    command: /bin/bash -c "envsubst < etc/nginx/nginx.template.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
  
  backend:
    build:
      context: .
    restart: always
    ports:
      - '5000:5000'
    environment:
       NODE_ENV: production
    env_file:
      - ./.env
    depends_on:
      - pgdb
    container_name: mee-backend
  
  client:
    build:
      context: ../mee
    restart: always
    ports:
      - '3000:3000'
    environment:
       NODE_ENV: production
    container_name: mee-client

  landing:
    build:
      context: ../mee-landing
    restart: always
    ports:
      - '3001:3001'
    environment:
       NODE_ENV: production
    container_name: mee-landing


volumes:
  pgdata: