services:
  pgdb:
    image: postgres:latest
    restart: on-failure
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    container_name: mee-postgres
  
  proxy:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      # - client
    container_name: mee-proxy
  
  backend:
    build:
      context: .
    restart: always
    ports:
      - '5000:5000'
    environment:
       NODE_ENV: production
    env_file:
      - ./.env
    depends_on:
      - pgdb
    container_name: mee-backend

volumes:
  pgdata:

  # client:
  #   image: node:latest
  #   restart: always
  #   ports:
  #     - '3000:3000'
  #   working_dir: /app
  #   volumes:
  #     - ./client:/app
  #   command: npm start
  #   depends_on:
  #     - pgdb